"""
morpho_analysis.py
----------------------------------------
Analyzes and visualizes the evolution of vascular structures
generated by the Synthetic Cambium Growth Loop.

Outputs:
1. Conductivity improvement curve
2. Morphological timeline (image grid)
3. Optional latent drift visualization (if latent data available)
"""

import os, numpy as np, matplotlib.pyplot as plt
from PIL import Image

# --- Config ---
RESULTS_DIR = os.path.join("results", "cambium_growth")
SAVE_DIR = os.path.join("results", "morpho_analysis")
os.makedirs(SAVE_DIR, exist_ok=True)

# ===============================================================
# 1️⃣ Conductivity curve
# ===============================================================

def plot_conductivity_curve():
    path = os.path.join(RESULTS_DIR, "conductivity_history.txt")
    if not os.path.exists(path):
        raise FileNotFoundError("Conductivity history not found. Run synthetic_cambium.py first.")
    
    data = np.loadtxt(path)
    plt.figure(figsize=(6,4))
    plt.plot(data, color="black", lw=2)
    plt.title("Conductivity Improvement Over Growth Iterations")
    plt.xlabel("Iteration")
    plt.ylabel("Effective Conductivity")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    savepath = os.path.join(SAVE_DIR, "conductivity_curve.png")
    plt.savefig(savepath, dpi=300)
    plt.close()
    print(f"✅ Conductivity curve saved to {savepath}")
    return savepath


# ===============================================================
# 2️⃣ Morphological timeline
# ===============================================================

def create_morphology_timeline(max_images=10):
    """
    Creates a horizontal strip showing morphology changes across iterations.
    """
    imgs = sorted([f for f in os.listdir(RESULTS_DIR) if f.startswith("growth_") and f.endswith(".png")])
    imgs = imgs[:max_images]
    if not imgs:
        raise FileNotFoundError("No growth images found in results/cambium_growth")

    images = [Image.open(os.path.join(RESULTS_DIR, f)).convert("L") for f in imgs]
    widths, heights = zip(*(img.size for img in images))
    total_width = sum(widths)
    max_height = max(heights)

    timeline = Image.new("L", (total_width, max_height))
    x_offset = 0
    for img in images:
        timeline.paste(img, (x_offset, 0))
        x_offset += img.size[0]

    savepath = os.path.join(SAVE_DIR, "morphology_timeline.png")
    timeline.save(savepath)
    print(f"✅ Morphological timeline saved to {savepath}")
    return savepath


# ===============================================================
# 3️⃣ Optional: Latent drift visualization (if latent.npy exists)
# ===============================================================

def plot_latent_drift(latent_path="results/latent_history.npy"):
    """
    Projects latent evolution in 2D if recorded.
    """
    if not os.path.exists(latent_path):
        print("ℹ️ No latent history found. Skipping latent drift visualization.")
        return None
    
    try:
        from umap import UMAP
    except ImportError:
        print("⚠️ UMAP not installed. Run `pip install umap-learn` to enable latent drift plotting.")
        return None

    z_hist = np.load(latent_path)
    reducer = UMAP(n_neighbors=5, min_dist=0.2, random_state=42)
    proj = reducer.fit_transform(z_hist)

    plt.figure(figsize=(5,5))
    plt.scatter(proj[:,0], proj[:,1], c=np.arange(len(proj)), cmap="viridis", s=20)
    plt.colorbar(label="Iteration")
    plt.title("Latent Drift During Growth")
    plt.tight_layout()
    savepath = os.path.join(SAVE_DIR, "latent_drift.png")
    plt.savefig(savepath, dpi=300)
    plt.close()
    print(f"✅ Latent drift plot saved to {savepath}")
    return savepath


# ===============================================================
# Main
# ===============================================================

def main():
    print("📊 Running Morphological Analytics...")
    curve = plot_conductivity_curve()
    timeline = create_morphology_timeline()
    drift = plot_latent_drift()

    print("\n✅ Morphological analysis complete.")
    print(f" - Conductivity curve: {curve}")
    print(f" - Morphology timeline: {timeline}")
    if drift: print(f" - Latent drift plot: {drift}")


if __name__ == "__main__":
    main()
